"""empty message

Revision ID: 023ce432420f
Revises: d70efa9486e1
Create Date: 2025-01-15 23:28:08.528284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023ce432420f'
down_revision = 'd70efa9486e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
