"""empty message

Revision ID: 581253618080
Revises: 5d38dbe130f5
Create Date: 2025-01-15 02:46:47.043071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581253618080'
down_revision = '5d38dbe130f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
