"""empty message

Revision ID: d70a443eaad0
Revises: 057f5bb2bee3
Create Date: 2025-01-12 19:05:57.493291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70a443eaad0'
down_revision = '057f5bb2bee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_constraint('student_courses_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('student_courses_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'students', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('topics_module_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topics_module_id_fkey', 'modules', ['module_id'], ['id'])

    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_courses_user_id_fkey', 'students', ['user_id'], ['id'])
        batch_op.create_foreign_key('student_courses_course_id_fkey', 'courses', ['course_id'], ['id'])

    op.drop_table('resources')
    # ### end Alembic commands ###
